# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-table-python-quickstart
metadata:
  template: cosmos-db-table-python-quickstart
services:
  web:
    project: ./src
    language: python
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
pipeline:
  provider: github
hooks:
  postprovision:
    posix:
      shell: sh
      interactive: true
      continueOnError: false
      run: |
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=\"$CONFIGURATION__AZURECOSMOSDB__ENDPOINT\"
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=\"$CONFIGURATION__AZURECOSMOSDB__TABLENAME\"
        " > ./src/.env
    windows:
      shell: pwsh
      interactive: true
      continueOnError: false
      run: |
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=""$env:CONFIGURATION__AZURECOSMOSDB__ENDPOINT""
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=""$env:CONFIGURATION__AZURECOSMOSDB__TABLENAME""
        " > ./src/.env